version: 2

sources:
  - name: public
    tables:
      - name: dimemployee
      - name: dimclass
      - name: dimstudent
      - name: dimsubject
      - name: dimterm
      - name: dimgradingscale
      - name: factstudentperformance
      - name: factattendance
      - name: factpayment
      - name: taughtby

models:
  - name: dim_employee_core
    columns:
      - name: employeeid
        tests:
          - unique
          - not_null

  - name: dim_class_core
    columns:
      - name: classid
        tests:
          - unique
          - not_null
      - name: classteacherid
        tests:
          - relationships:
              to: ref('dim_employee_core')
              field: employeeid

  - name: dim_student_core
    columns:
      - name: studentid
        tests:
          - unique
          - not_null
      - name: classid
        tests:
          - relationships:
              to: ref('dim_class_core')
              field: classid

  - name: dim_subject_core
    columns:
      - name: subjectid
        tests:
          - unique
          - not_null

  - name: dim_term_core
    columns:
      - name: termid
        tests:
          - unique
          - not_null

  - name: dim_gradingscale_core
    columns:
      - name: gradeid
        tests:
          - unique
          - not_null

  - name: fact_studentperformance_core
    columns:
      - name: studentid
        tests:
          - not_null
          - relationships:
              to: ref('dim_student_core')
              field: studentid
      - name: subjectid
        tests:
          - not_null
          - relationships:
              to: ref('dim_subject_core')
              field: subjectid
      - name: termid
        tests:
          - not_null
          - relationships:
              to: ref('dim_term_core')
              field: termid
      - name: gradeid
        tests:
          - not_null
          - relationships:
              to: ref('dim_gradingscale_core')
              field: gradeid

  - name: fact_attendance_core
    columns:
      - name: studentid
        tests:
          - not_null
          - relationships:
              to: ref('dim_student_core')
              field: studentid
      - name: classid
        tests:
          - not_null
          - relationships:
              to: ref('dim_class_core')
              field: classid
      - name: termid
        tests:
          - not_null
          - relationships:
              to: ref('dim_term_core')
              field: termid

  - name: fact_payment_core
    columns:
      - name: paymentid
        tests:
          - unique
          - not_null
      - name: studentid
        tests:
          - not_null
          - relationships:
              to: ref('dim_student_core')
              field: studentid
      - name: termid
        tests:
          - not_null
          - relationships:
              to: ref('dim_term_core')
              field: termid
      - name: paymentstatus
        description: "Overall payment status"
        tests:
          - not_null
          - accepted_values:
              values: ['Paid', 'Partial', 'Unpaid']

  - name: taughtby_core
    columns:
      - name: employeeid
        tests:
          - not_null
          - relationships:
              to: ref('dim_employee_core')
              field: employeeid
      - name: classid
        tests:
          - not_null
          - relationships:
              to: ref('dim_class_core')
              field: classid
      - name: subjectid
        tests:
          - not_null
          - relationships:
              to: ref('dim_subject_core')
              field: subjectid
  - name: attendance_summary_mart
    description: "Attendance summary per student per term"
    columns:
      - name: studentid
        description: "Unique identifier for the student"
        tests:
          - not_null
      - name: termid
        description: "Unique identifier for the term"
        tests:
          - not_null
      - name: total_days
        description: "Total distinct days attendance was recorded"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: days_present
        description: "Number of days the student was marked present"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: attendance_rate_pct
        description: "Percentage of attendance"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0 AND attendance_rate_pct <= 100"

  - name: payment_summary_mart
    description: "Payment summary per student per term"
    columns:
      - name: studentid
        tests:
          - not_null
      - name: termid
        tests:
          - not_null
      - name: total_amount_paid
        description: "Total amount paid by the student for the term"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"
  - name: student_performance_mart
    description: "Academic performance summary per student per term"
    columns:
      - name: studentid
        tests:
          - not_null
      - name: termid
        tests:
          - not_null
      - name: term_gpa
        description: "Term gpa score of the student in the term"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0 AND term_gpa <= 5"
      - name: cgpa
        description: "CGPA calculated based on scores"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0 AND cgpa <= 5"

  - name: employee_teaching_load_mart
    description: "Summary of employee teaching load"
    columns:
      - name: employeeid
        tests:
          - not_null
      - name: total_classes
        description: "Number of classes assigned to the employee"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: total_subjects
        description: "Number of distinct subjects taught by the employee"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"


